apiVersion: skaffold/v2beta26
kind: Config
build:
  local:
    tryImportMissing: true
  artifacts:
  - image: alpine
    custom:
      buildCommand: echo
      # Needed in order to make skaffold file sync respect .dockerignore
      dependencies:
        dockerfile:
          path: Dockerfile
    context: .
    sync:
      # Needed in order to make skaffold file sync respect .dockerignore
      infer:
        - '**/*'
#      manual:
#      - src: '**/*'
#        dest: /src/test
deploy:
  kubeContext: gke_kubeflow-platform_europe-west1-d_kf-test
  kubectl:
    manifests:
    - skaffold/deployment.yaml
    hooks:
      after:
        - host:
            command: [ "./skaffold/hack-touch.sh"]
