apiVersion: skaffold/v2beta26
kind: Config
build:
  local:
    tryImportMissing: true
  artifacts:
  - image: alpine
    custom:
      buildCommand: echo
    context: .
    sync:
      manual:
        - src: '**/*'
          dest: /src/test
deploy:
  kubeContext: gke_kubeflow-platform_europe-west1-d_kf-test
  kubectl:
    manifests:
    - skaffold/deployment.yaml
    hooks:
      after:
        - host:
            command: [ "./skaffold/hack-touch.sh"]
