---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dxia
  name: dxia-test
spec:
  selector:
    matchLabels:
      name: dxia-test
  replicas: 2
  template:
    metadata:
      labels:
        name: dxia-test
    spec:
      containers:
      - name: dxia-test
        image: alpine:3.15.0-rc.4@sha256:fb150366bfb5a297a7f8852e0cec462a12f638374f8a04ad235c56a97e780add
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
