---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dxia
  name: dxia-test
spec:
  selector:
    matchLabels:
      name: dxia-test
  replicas: 1
  template:
    metadata:
      labels:
        name: dxia-test
    spec:
      containers:
      - name: dxia-test
        image: alpine
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
